### PR TITLE
PPSE-912: upgrade version for next release

### PR DESCRIPTION
**Pull request by manginav**
### Description 
Upgrading version to 0.10.9

### ticket 
https://arcpublishing.atlassian.net/browse/PPSE-912

### CODE REVIEW

**Comment by manginav** [comment]
@mfattoru , @darful , @calexicoz , @jodieburnett , @cmmovius , @anscho : I am not able to add pub-stack engineers directly to the PR . may be its beacuse I am doing this PR form my fork. Anyhow this is a followup for previous change in typo. Created a new version 0.10.9 as per here https://github.com/washingtonpost/ans-schema#creating-a-new-ans-version.

**Comment by mfattoru** [comment]
@manginav Could you update the release numbers in the readme file into 
```
The current production version of ANS is 0.10.8
The current development version of ANS is 0.10.9
```

**Comment by manginav** [comment]
> @manginav Could you update the release numbers in the readme file into
> 
> ```
> The current production version of ANS is 0.10.8
> The current development version of ANS is 0.10.9
> ```

Sure Michele Done.

**Review by mfattoru — APPROVED** [review]

**Comment by manginav** [comment]
thanks for merging for me Michele

**Pull request merged**
