### PR TITLE
Proposal: Line Count Planning

### PR DESCRIPTION
**Pull request by brendaneamon**
This PR is for a simple change that will ensure consistency in how story length data are ingested and processed by WebSked.

### CODE REVIEW

**Comment by jpblair** [comment]
@brendaneamon In your example, `story_length` is a top-level key, instead of a subobject under `planning`.  I assume this is a typo?

**Comment by brendaneamon** [comment]
@jpblair, yes that was definitely unintentional—I went ahead and made a correction.

**Comment by gengel** [comment]
Are inches normally used as the height metric in non-US newspapers?

**Comment by jpblair** [comment]
I'm not sure, but inches are already part of the schema - what Brendan is looking to add is lines.

**Comment by RyanGladstone** [comment]
@gengel I asked Willi. He said that lines are the most common unit in use. 

He says that some European publishers measure in modules, but isn't sure if that's still a common practice.

A few publishers measure in [cicero](https://en.wikipedia.org/wiki/Cicero_(typography)) or picas https://en.wikipedia.org/wiki/Pica_(typography)).

**Comment by RyanGladstone** [comment]
A representative of Le Parisien said that they use "character count, including spaces" to measure story length.

**Pull request merged**
