### PR TITLE
Move dev deps to devDependencies section in package.json

### PR DESCRIPTION
**Pull request by dannycao**

### CODE REVIEW

**Comment by manginav** [comment]
HI @dannycao I made these changes in another PR [here](https://github.com/washingtonpost/ans-schema/pull/282) if it is not urgent change you can close this PR

**Comment by dannycao** [comment]
> HI @dannycao I made these changes in another PR [here](https://github.com/washingtonpost/ans-schema/pull/282) if it is not urgent change you can close this PR

Hi @manginav, no it is not urgent so I'll close this PR. However, I don't see these changes in your PR?
Sorry should've provided this in the PR description, but for context: our service depends on this package which currently includes `mocha` and an `npm audit` on our service shows this version of mocha has dependencies which have security vulnerabilities, so wanted to change so the published packaged doesn't include dev/test dependencies. Should probably upgrade `mocha`.

**Comment by manginav** [comment]
> > HI @dannycao I made these changes in another PR [here](https://github.com/washingtonpost/ans-schema/pull/282) if it is not urgent change you can close this PR
> 
> Hi @manginav, no it is not urgent so I'll close this PR. However, I don't see these changes in your PR? Sorry should've provided this in the PR description, but for context: our service depends on this package which currently includes `mocha` and an `npm audit` on our service shows this version of mocha has dependencies which have security vulnerabilities, so wanted to change so the published packaged doesn't include dev/test dependencies. Should probably upgrade `mocha`.

I am approving this PR nevertheless to avoid any confusions @dannycao , I will try to merge these changes into my PR then

**Review by manginav — APPROVED** [review]

**Comment by dannycao** [comment]
Closing PR, these changes will be made separately by @manginav .

**Pull request closed without merging**
