### PR TITLE
PPSE-912: flipped author and site schema in operations schema

### PR DESCRIPTION
**Pull request by manginav**
### Description 
Schemas are flipped between author and site, so flipped them back

### CODE REVIEW

**Comment by mfattoru** [comment]
If this error was introduced in 0.10.0, should this fix all versions from 0.10.0 and up?

**Comment by manginav** [comment]
> If this error was introduced in 0.10.0, should this fix all versions from 0.10.0 and up?

Hi @mfattoru I am not sure, but this is same across all the versions. But since they have pointed for 0.10.0 I have made the change for all the version up. In any case it is typo so it would be good to fix it is what I thought

**Comment by mfattoru** [comment]
I also just merged in 0.10.8 that needs to be updated. Also, We might want to wait for someone else comments, as I'm not sure how issues on older releases should be tackled

**Comment by manginav** [comment]
> I also just merged in 0.10.8 that needs to be updated. Also, We might want to wait for someone else comments, as I'm not sure how issues on older releases should be tackled

added changes for 0.10.8 @mfattoru  👍

**Comment by manginav** [comment]
Hi @mfattoru  I have changed this to only for versions 0.10.0 and 0.10.8

**Comment by manginav** [comment]
done with your suggestion @mfattoru

**Review by mfattoru — APPROVED** [review]

**Pull request merged**
