### PR TITLE
EL-2625: Proposal for Table of Contents Anchor links

### PR DESCRIPTION
**Pull request by michaelguild13**
This is the init proposal for TOC and anchor links

### CODE REVIEW

**Comment by michaelguild13** [comment]
Has everyone been able to reviews this yet?

**Comment by michaelguild13** [comment]
If no one has issues with this proposal, I would like to merge and start writing the schema.
@gengel @chadmoone

**Comment by st421** [comment]
When I see the name `anchor`, I think of an html tag that can link to anything (i.e. it would not be clear to me that this is limited to items within the current document). I think something like `internal_link` might make the functionality more clear. On the other hand, it's not uncommon for clients to want elements that do have links to external content so something more generic that would allow for internal or external linking might be useful.

**Comment by chadmoone** [comment]
I previously approved, and still good with this. Personally I think the term `anchor` is fine because it's part of ANS, and it makes sense to me that it would be limited to anchor to an ANS content element.

**Comment by gengel** [comment]
@design1online An interstitial link is an element that represents a link out to another story. 

An anchor *property* on an element represents a way of linking *to* an element within a story. It's roughly equivalent to an HTML name/id. (You could populate the name/id in your example from the anchor property on an element.) Because it's a property, it can be applied to any content element, including an interstitial_link.

**Comment by design1online** [comment]
@gengel true, but we also have clients that are using it to reference external links (RTL is one that actually wants functionality for their interstitial links to open in an external window, and I believe Raycom has asked for this before too).

For instance, in Ellipsis you can create a link to any URL and that is saved as an interstitial link in the ANS. I'm not sure why we need another ANS element for what is essentially already doing the same thing. I think updating the interstitial link to include the anchor/target/title/id/name properties makes more sense.

**Comment by gengel** [comment]
@design1online 

I think the use of the name "anchor" here and the fact that HTML uses the "a" tag for two different things--to mark text as a link-to-something-else, and as something-that-can-be-linked-to --is causing some confusion. 

This is not creating a new way to link out to another story -- it's creating a reference point for other links to link to, and a mechanism for editors (and if they want, front-end renders) to generate a table of contents for a document. 

It's also proposed to be implemented as a trait on any content element. So you could assign an anchor to an interstitial link in Ellipsis, and this would effectively give you what you're suggesting (a name/id/title property on an interstitial link.)

**Comment by michaelguild13** [comment]
@gengel @chadmoone @design1online
Proposal has been updated

**Pull request closed without merging**
